<?php
declare(strict_types=1);
require __DIR__ . '/auth.php';
require_authentication();
require __DIR__ . '/layout.php';

function booking_downloads_load(string $path): ?array { $json = is_file($path) ? file_get_contents($path) : false; $data = is_string($json) ? json_decode($json, true) : null; return is_array($data) ? $data : null; }
function booking_downloads_row(array $item, int $index): void { $p = 'items[' . escape_html((string) $item['id']) . ']'; ?>
<section class="concert-row"><div class="concert-row__head"><h2><?= escape_html((string) $item['label']) ?></h2><label class="remove-toggle"><input type="checkbox" name="<?= $p ?>[remove]" value="1"> <span>Material entfernen</span></label></div><div class="concert-grid">
<input type="hidden" name="<?= $p ?>[id]" value="<?= escape_html((string) $item['id']) ?>"><input type="hidden" name="<?= $p ?>[path]" value="<?= escape_html((string) $item['path']) ?>"><input type="hidden" name="<?= $p ?>[managedUpload]" value="<?= !empty($item['managedUpload']) ? '1' : '0' ?>">
<label class="field"><span>Bezeichnung</span><input name="<?= $p ?>[label]" value="<?= escape_html((string) $item['label']) ?>" maxlength="160" required></label><label class="field"><span>Spalte</span><select name="<?= $p ?>[column]"><option value="left" <?= $item['column'] === 'left' ? 'selected' : '' ?>>Links</option><option value="right" <?= $item['column'] === 'right' ? 'selected' : '' ?>>Rechts</option></select></label><label class="field"><span>Reihenfolge</span><input type="number" min="1" name="<?= $p ?>[order]" value="<?= $index + 1 ?>" required></label>
<label class="field field--wide"><span>Gespeicherte Datei</span><input value="<?= escape_html((string) $item['path']) ?>" readonly><small class="field-help">Zum Ersetzen nur PDF oder ZIP auswählen. Die bisherige verwaltete Datei wird erst nach erfolgreichem Speichern gelöscht.</small></label><label class="field field--wide"><span>Datei ersetzen (optional)</span><input type="file" name="replace_<?= escape_html((string) $item['id']) ?>" accept=".pdf,.zip,application/pdf,application/zip"></label>
</div></section><?php }
$items = booking_downloads_load(dirname(__DIR__) . '/data/booking-downloads.json');
?>
<!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="robots" content="noindex, nofollow"><title>Booking-Material | Mélange à Deux &amp; Amis</title><script src="admin-theme.js"></script><link rel="stylesheet" href="admin.css"></head><body class="admin-page"><?php render_admin_layout_open('booking-material'); ?><header class="admin-content-header"><p class="admin-kicker">Booking-Material</p><h1>Booking-Material verwalten</h1><p class="admin-muted">Downloads aus <code>data/booking-downloads.json</code>. Der Link „Referenzen“ wird bewusst nicht hier verwaltet.</p></header>
<?php if (isset($_GET['saved'])): ?><p class="admin-message admin-message--success">Das Booking-Material wurde gespeichert.</p><?php endif; ?>
<?php if ($items === null): ?><p class="admin-message admin-message--error">Die Download-Daten konnten nicht gelesen werden. Speichern ist deaktiviert.</p><?php else: ?><form method="post" action="save-booking-downloads.php" enctype="multipart/form-data"><input type="hidden" name="csrf_token" value="<?= escape_html(csrf_token()) ?>"><?php foreach ($items as $i => $item) { if (is_array($item)) booking_downloads_row($item, $i); } ?><section class="concert-row"><h2>Neues Material hochladen</h2><div class="concert-grid"><label class="field"><span>Bezeichnung</span><input name="new_label" maxlength="160"></label><label class="field"><span>Spalte</span><select name="new_column"><option value="left">Links</option><option value="right">Rechts</option></select></label><label class="field"><span>Reihenfolge</span><input type="number" min="1" name="new_order" value="99"></label><label class="field field--wide"><span>PDF- oder ZIP-Datei</span><input type="file" name="new_upload" accept=".pdf,.zip,application/pdf,application/zip"><small class="field-help">Dateien werden ausschließlich unter <code>assets/downloads/booking/managed/</code> gespeichert.</small></label></div></section><div class="admin-actions"><button class="admin-button" type="submit">Booking-Material speichern</button></div></form><?php endif; ?><?php render_admin_layout_close(); ?></body></html>
